const plans=[
{name:'Demo Plan',short:'DEMO',amount:'₹300',min:300,max:300,rate:'5%',period:'Every Hour',duration:'For 10 Hours',refs:'1 Referral Required',accent:'#22c55e',growth:15,total:'₹450.00'},
{name:'Silver Plan',short:'SILVER',amount:'₹1,000 - ₹10,000',min:1000,max:10000,rate:'10%',period:'Every Day',duration:'For 7 Days',refs:'2 Referrals Required',accent:'#38bdf8',growth:500,total:'₹8,500.00'},
{name:'Gold Plan',short:'GOLD',amount:'₹20,000 - ₹50,000',min:20000,max:50000,rate:'10%',period:'Every Day',duration:'For 7 Days',refs:'2 Referrals Required',accent:'#f5b400',growth:2500,total:'₹42,500.00',popular:true},
{name:'Platinum Plan',short:'PLATINUM',amount:'₹1,00,000 - ₹2,00,000',min:100000,max:200000,rate:'10%',period:'Every Week',duration:'For 5 Weeks',refs:'3 Referrals Required',accent:'#d946ef',growth:10000,total:'₹1,50,000.00'},
{name:'Diamond Plan',short:'DIAMOND',amount:'₹2,00,000 - ₹10,00,000',min:200000,max:1000000,rate:'10%',period:'Every Week',duration:'For 5 Weeks',refs:'3 Referrals Required',accent:'#22d3ee',growth:20000,total:'₹3,00,000.00'}
];
const deposits=[['Aman Kumar','₹5,000','Silver Plan','Pending'],['Rohit Sharma','₹20,000','Gold Plan','Pending'],['Vikash Yadav','₹2,000','Silver Plan','Approved'],['Sunil Patel','₹50,000','Gold Plan','Approved'],['Karan Singh','₹1,20,000','Platinum Plan','Pending']];
const withdraws=[['Aman Kumar','₹3,500','Pending'],['Rohit Sharma','₹10,000','Pending'],['Vikash Yadav','₹2,000','Approved'],['Sunil Patel','₹25,000','Rejected'],['Karan Singh','₹15,000','Pending']];
function money(n){return '₹'+Number(n).toLocaleString('en-IN')+'.00'}
function renderPlans(){const grid=document.getElementById('plansGrid');const modal=document.getElementById('modalPlans');grid.innerHTML='';modal.innerHTML='';plans.forEach((p,i)=>{const card=document.createElement('div');card.className='plan-card '+(p.popular?'gold':'');card.style.setProperty('--accent',p.accent);card.innerHTML=`${p.popular?'<span class="badge">MOST POPULAR</span>':''}<h3>${p.short} PLAN</h3><div class="rate">${p.rate}</div><p><b>${p.period}</b><br>${p.duration}</p><small>Range ${p.amount}</small><small><br>${p.refs}</small><button onclick="selectPlan(${i})">View Plan</button>`;grid.appendChild(card);const opt=document.createElement('div');opt.className='modal-option';opt.innerHTML=`<div><b style="color:${p.accent}">${p.name}</b><p>${p.rate} ${p.period} • ${p.duration} • ${p.refs}</p></div><button onclick="selectPlan(${i});closePlanModal()">Select</button>`;modal.appendChild(opt);});}
function selectPlan(i){const p=plans[i];const amount=p.popular?25000:p.min;document.getElementById('activePlanName').textContent=p.name;document.getElementById('activePlanRate').textContent=`${p.rate} ${p.period} ${p.duration}`;document.getElementById('activeAmount').textContent=money(amount);document.getElementById('activeGrowth').textContent=money(p.growth);document.getElementById('activeProfit').textContent=p.total;document.getElementById('totalInvested').textContent=money(amount);document.getElementById('totalProfit').textContent=p.total;document.getElementById('totalBalance').textContent=money(amount+parseInt(p.total.replace(/[₹,.]/g,'')));document.getElementById('refReq').textContent=p.refs;toast(`${p.name} loaded in demo dashboard`)}
function renderTables(){const dep=document.getElementById('depositTable');const wit=document.getElementById('withdrawTable');dep.innerHTML='';deposits.forEach(r=>{dep.innerHTML+=`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="status ${r[3].toLowerCase()}">${r[3]}</span></td><td><div class="mini-actions"><button onclick="adminToast('Approved')">✓</button><button onclick="adminToast('Rejected')">×</button></div></td></tr>`});wit.innerHTML='';withdraws.forEach(r=>{wit.innerHTML+=`<tr><td>${r[0]}</td><td>${r[1]}</td><td><span class="status ${r[2].toLowerCase()}">${r[2]}</span></td><td><div class="mini-actions"><button onclick="adminToast('Approved')">✓</button><button onclick="adminToast('Rejected')">×</button></div></td></tr>`});}
function openPlanModal(){document.getElementById('planModal').classList.add('show')}function closePlanModal(){document.getElementById('planModal').classList.remove('show')}function scrollToPlans(){document.getElementById('plans').scrollIntoView({behavior:'smooth'})}function showDemoLogin(){toast('Demo login preview only')}function copyReferral(){navigator.clipboard?.writeText('https://demo.local/ref/AMAN001');toast('Demo referral link copied')}function adminToast(m){toast('Admin demo action: '+m)}function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
let sec=37215;setInterval(()=>{sec--;let h=String(Math.floor(sec/3600)).padStart(2,'0'),m=String(Math.floor(sec%3600/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');document.getElementById('timer').textContent=`${h} : ${m} : ${s}`},1000);
renderPlans();renderTables();
